spring:
  application:
    name: spring-boot-boilerplate
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false # enabled in application-dev.yaml
    open-in-view: false
  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}
  flyway:
    schemas:
      - auth
    create-schemas: true
  session:
    timeout: 30m

server:
  port: 8181
  servlet:
    session:
      cookie:
        name: SESSION
        http-only: true
        secure: true # set to false in application-dev.yaml for local HTTP
        same-site: LAX

logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR